---
appveyor.yml:
  delete: true

.travis.yml:
  delete: true

.gitlab-ci.yml:
  delete: true

Gemfile:
  required:
    ':development':
      - gem: 'rspec-mocks'
        version: '~> 3.8'
      - gem: 'rest-client'
        version: '~> 2.0'
      - gem: 'rschema'
        version: '~> 3.0'
